# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{contentment}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bob Larrick"]
  s.date = %q{2011-01-12}
  s.description = %q{Rails Engine for dead simple content management.  }
  s.email = %q{larrick@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "config/routes.rb",
    "lib/contentment.rb",
    "lib/contentment/engine.rb",
    "lib/extensions/action_controller/base.rb",
    "lib/generators/contentment/contentment_views_templates/contents/_preview.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents/edit.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents/index.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents/new.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents/show.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents_helper.rb",
    "lib/generators/contentment/templates/content.rb",
    "lib/generators/contentment/templates/content_test.rb",
    "lib/generators/contentment/templates/contents_controller.rb",
    "lib/generators/contentment/templates/migration.rb",
    "lib/generators/contentment_generator.rb",
    "lib/generators/contentment_views_generator.rb"
  ]
  s.homepage = %q{https://github.com/deathbob/Contentment}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{contentment}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Dead simple content management.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

