# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "contentment"
  s.version = "0.7.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bob Larrick"]
  s.date = "2012-09-17"
  s.description = "Rails Engine for simple content management.  See readme on github for details."
  s.email = "larrick@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "config/routes.rb",
    "lib/contentment.rb",
    "lib/contentment/engine.rb",
    "lib/extensions/action_controller/base.rb",
    "lib/generators/contentment/contentment_views_templates/contents/_form.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents/_preview.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents/edit.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents/index.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents/new.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents/show.html.erb",
    "lib/generators/contentment/contentment_views_templates/contents_helper.rb",
    "lib/generators/contentment/templates/content.rb",
    "lib/generators/contentment/templates/content_test.rb",
    "lib/generators/contentment/templates/contents_controller.rb",
    "lib/generators/contentment/templates/migration.rb",
    "lib/generators/contentment_generator.rb",
    "lib/generators/contentment_views_generator.rb"
  ]
  s.homepage = "https://github.com/deathbob/Contentment"
  s.require_paths = ["lib"]
  s.rubyforge_project = "contentment"
  s.rubygems_version = "1.8.24"
  s.summary = "Rails Engine for simple content management."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

